@echo off
echo Building ...
docker build -t home_server .
echo Saving ...
docker save home_server -o home_server.tar
REM echo Loading ...
REM docker load -i home_server.tar
REM echo Running ...
REM docker run -d -p 80:80 --name home_server home_server
pause
